-- Migration: Add Command Queue System
-- Purpose: Enable IDE extensions to poll for commands and report status
-- Tables: ide_devices (device registration), commands (command queue)

-- IDE Devices Table
-- Stores registered IDE instances (VSCode, WebStorm, etc.)
CREATE TABLE IF NOT EXISTS ide_devices (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id TEXT NOT NULL,
  device_name TEXT, -- e.g., "MacBook Pro" or "Work PC"
  ide_type TEXT NOT NULL, -- 'vscode', 'webstorm', 'cursor'
  device_id TEXT NOT NULL UNIQUE, -- Generated by extension
  api_key_hash TEXT NOT NULL, -- Hashed API key for auth
  last_seen TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'online', -- 'online', 'offline'
  metadata JSONB DEFAULT '{}', -- IDE version, OS, etc.
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast lookups by user
CREATE INDEX idx_ide_devices_user_id ON ide_devices(user_id);
-- Index for device polling
CREATE INDEX idx_ide_devices_device_id ON ide_devices(device_id);
-- Index for status checks
CREATE INDEX idx_ide_devices_status ON ide_devices(status, last_seen);

-- Commands Table
-- Command queue for IDE extensions to poll and execute
CREATE TABLE IF NOT EXISTS commands (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id TEXT NOT NULL,
  device_id UUID REFERENCES ide_devices(id) ON DELETE CASCADE,
  command_type TEXT NOT NULL, -- 'IMPORT_PROJECT', 'ANALYZE_WORKSPACE', 'SYNC_CHANGES', 'APPLY_CHANGES'
  project_id UUID, -- Optional: references projects table if exists
  payload JSONB NOT NULL DEFAULT '{}', -- Command-specific data
  status TEXT DEFAULT 'pending', -- 'pending', 'executing', 'completed', 'failed'
  priority INTEGER DEFAULT 0, -- Higher = more urgent
  result JSONB, -- Result data from extension
  error_message TEXT, -- Error details if failed
  created_at TIMESTAMPTZ DEFAULT NOW(),
  started_at TIMESTAMPTZ, -- When extension started executing
  completed_at TIMESTAMPTZ, -- When execution finished
  expires_at TIMESTAMPTZ -- Commands can expire if not executed
);

-- Index for efficient polling (device + status + priority)
CREATE INDEX idx_commands_poll ON commands(device_id, status, priority DESC, created_at);
-- Index for project commands
CREATE INDEX idx_commands_project ON commands(project_id, status);
-- Index for cleanup (expired commands)
CREATE INDEX idx_commands_expires ON commands(expires_at) WHERE expires_at IS NOT NULL;
-- Index for user's command history
CREATE INDEX idx_commands_user ON commands(user_id, created_at DESC);

-- Command History View (for web app)
CREATE OR REPLACE VIEW command_history AS
SELECT 
  c.id,
  c.user_id,
  c.command_type,
  c.project_id,
  c.status,
  c.created_at,
  c.completed_at,
  c.error_message,
  d.device_name,
  d.ide_type,
  EXTRACT(EPOCH FROM (c.completed_at - c.started_at)) as execution_time_seconds
FROM commands c
LEFT JOIN ide_devices d ON c.device_id = d.id
ORDER BY c.created_at DESC;

-- Function to update device last_seen timestamp
CREATE OR REPLACE FUNCTION update_device_last_seen()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE ide_devices 
  SET last_seen = NOW(), status = 'online'
  WHERE id = NEW.device_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update last_seen when command is polled/updated
CREATE TRIGGER trigger_update_device_last_seen
AFTER UPDATE ON commands
FOR EACH ROW
WHEN (NEW.status = 'executing' OR NEW.status = 'completed' OR NEW.status = 'failed')
EXECUTE FUNCTION update_device_last_seen();

-- Function to mark devices offline if not seen recently
CREATE OR REPLACE FUNCTION mark_inactive_devices_offline()
RETURNS void AS $$
BEGIN
  UPDATE ide_devices
  SET status = 'offline'
  WHERE last_seen < NOW() - INTERVAL '30 seconds'
    AND status = 'online';
END;
$$ LANGUAGE plpgsql;

-- Function to cleanup expired commands
CREATE OR REPLACE FUNCTION cleanup_expired_commands()
RETURNS void AS $$
BEGIN
  DELETE FROM commands
  WHERE expires_at IS NOT NULL 
    AND expires_at < NOW()
    AND status = 'pending';
END;
$$ LANGUAGE plpgsql;

-- Grant permissions (adjust based on your auth setup)
-- GRANT SELECT, INSERT, UPDATE ON ide_devices TO authenticated;
-- GRANT SELECT, INSERT, UPDATE ON commands TO authenticated;
-- GRANT SELECT ON command_history TO authenticated;
