"use client";

import { AppLayout } from "@/components/layout/AppLayout";
import { Download, Github, Code, CheckCircle2, FileCode, Layers, Zap, Terminal, Key } from "lucide-react";
import { useState, useEffect } from "react";
import JSZip from "jszip";
import { saveAs } from "file-saver";

export default function ExportPage() {
    const [isExporting, setIsExporting] = useState(false);
    const [isCreatingRepo, setIsCreatingRepo] = useState(false);
    const [githubToken, setGithubToken] = useState('');
    const [repoUrl, setRepoUrl] = useState<string | null>(null);
    const [latestProject, setLatestProject] = useState<any>(null);

    // Fetch latest project on mount
    useEffect(() => {
        const fetchLatestProject = async () => {
            try {
                // We'll use the project service to get the latest project
                // For now, we can just fetch from the API or use the service directly if available
                // Since we are client-side, let's use the service pattern we established
                // But to avoid importing service logic here if not needed, let's just use a direct Supabase call or assume the user just came from Import

                // For MVP: Fetch from Supabase directly via client-side client if possible, 
                // or just use a simple API endpoint. 
                // Let's use the projectService if it's available and working.

                // Actually, let's just mock it for now or fetch from a new endpoint?
                // No, let's do it properly. We need the project ID.
                // Let's assume the user just imported a project.

                // Better approach for MVP: Fetch the list of projects and take the first one.
                // We can use the existing projectService.
                const { projectService } = await import('@/services/project.service');
                const projects = await projectService.getProjects();
                if (projects && projects.length > 0) {
                    setLatestProject(projects[0]);
                }
            } catch (error) {
                console.error("Failed to fetch latest project:", error);
            }
        };

        fetchLatestProject();
    }, []);

    // Mock project data for V1 (or use real data if available)
    const projectStats = {
        framework: "Next.js 14",
        components: 24,
        linesOfCode: 1450,
        importsFixed: 12
    };

    const handleDownload = async () => {
        setIsExporting(true);
        try {
            const zip = new JSZip();
            const rootName = latestProject?.name || "shift-project";
            const root = zip.folder(rootName);

            // Use UPG Blueprint if available, otherwise fallback to basic scaffolding
            const blueprint = latestProject?.blueprint || null;

            if (blueprint && blueprint.file_tree && blueprint.nodes) {
                console.log("[Export] Generating ZIP from UPG Blueprint...");
                
                const addFilesToZip = (treeNode: any, folder: any) => {
                    for (const [name, value] of Object.entries(treeNode)) {
                        if (typeof value === 'string') {
                            // It's a file node ID
                            const node = blueprint.nodes[value];
                            if (node && (node.type === 'file' || node.type === 'component')) {
                                folder.file(name, node.content || '');
                            }
                        } else if (typeof value === 'object') {
                            // It's a directory
                            const subFolder = folder.folder(name);
                            addFilesToZip(value, subFolder);
                        }
                    }
                };

                addFilesToZip(blueprint.file_tree, root);

                // Add package.json from metadata if available
                if (blueprint.project) {
                    root?.file("package.json", JSON.stringify({
                        name: blueprint.project.name.toLowerCase().replace(/[^a-z0-9]/g, '-'),
                        version: blueprint.project.version || "0.1.0",
                        dependencies: blueprint.project.dependencies || {}
                    }, null, 2));
                }
            } else {
                // Fallback basic scaffolding
                root?.file("package.json", JSON.stringify({
                    name: latestProject?.name?.toLowerCase().replace(/[^a-z0-9]/g, '-') || "shift-project",
                    version: "0.1.0",
                    private: true,
                    scripts: { "dev": "next dev", "build": "next build", "start": "next start" },
                    dependencies: { "react": "^18", "react-dom": "^18", "next": "14.0.4" }
                }, null, 2));

                root?.file("README.md", `# ${latestProject?.name || 'Shift AI Project'}\n\nGenerated by Shift AI`);
            }

            const content = await zip.generateAsync({ type: "blob" });
            saveAs(content, `${rootName}.zip`);
        } catch (error) {
            console.error("Export failed:", error);
            alert("Export failed. Please try again.");
        } finally {
            setIsExporting(false);
        }
    };


    const handlePushToGitHub = async () => {
        if (!githubToken) {
            alert('Please enter your GitHub Personal Access Token');
            return;
        }

        setIsCreatingRepo(true);
        try {
            // Get session token to authorize the API route
            const { authService } = await import('@/services/auth.service');
            const session = await authService.getSession();
            const accessToken = session?.access_token;

            const response = await fetch('/api/github/create-repo', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    projectId: latestProject?.id,
                    repoName: latestProject ? `shift-${latestProject.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}` : `shift-project-${Date.now()}`,
                    isPrivate: false,
                    githubToken,
                    accessToken // Pass the token
                })
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || 'Failed to create repository');
            }

            setRepoUrl(data.repoUrl);
            alert(`✅ Repository created!\n${data.repoUrl}`);
        } catch (error: any) {
            console.error("GitHub creation failed:", error);
            alert(`❌ Failed: ${error.message}`);
        } finally {
            setIsCreatingRepo(false);
        }
    };

    return (
        <AppLayout>
            <div className="space-y-8">
                <div>
                    <h1 className="text-2xl font-medium text-[var(--text-primary)]">Export Project</h1>
                    <p className="text-[13px] text-[var(--text-secondary)] mt-1">
                        Download or push to GitHub
                    </p>
                </div>

                <div className="glass-panel rounded-xl p-8 border border-[var(--border-subtle)] relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-64 h-64 bg-[var(--accent-primary)]/10 blur-3xl rounded-full pointer-events-none" />

                    <div className="relative z-10">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="h-10 w-10 rounded-full bg-[var(--accent-primary)]/10 flex items-center justify-center text-[var(--accent-primary)] shadow-[0_0_15px_var(--accent-glow)]">
                                <CheckCircle2 size={20} />
                            </div>
                            <div>
                                <h2 className="text-xl font-medium text-[var(--text-primary)]">Your project is ready</h2>
                                <p className="text-[13px] text-[var(--text-secondary)]">
                                    Clean structure. Correct imports. IDE-ready.
                                </p>
                            </div>
                        </div>

                        {/* Stats Grid */}
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                            <div className="p-4 rounded-lg bg-[var(--bg-root)] border border-[var(--border-subtle)]">
                                <div className="flex items-center gap-2 text-[var(--text-tertiary)] mb-1">
                                    <Layers size={14} />
                                    <span className="text-[11px] uppercase tracking-wider">Framework</span>
                                </div>
                                <div className="text-[15px] font-medium text-[var(--text-primary)]">
                                    {projectStats.framework}
                                </div>
                            </div>
                            <div className="p-4 rounded-lg bg-[var(--bg-root)] border border-[var(--border-subtle)]">
                                <div className="flex items-center gap-2 text-[var(--text-tertiary)] mb-1">
                                    <Code size={14} />
                                    <span className="text-[11px] uppercase tracking-wider">Components</span>
                                </div>
                                <div className="text-[15px] font-medium text-[var(--text-primary)]">
                                    {projectStats.components} Files
                                </div>
                            </div>
                            <div className="p-4 rounded-lg bg-[var(--bg-root)] border border-[var(--border-subtle)]">
                                <div className="flex items-center gap-2 text-[var(--text-tertiary)] mb-1">
                                    <FileCode size={14} />
                                    <span className="text-[11px] uppercase tracking-wider">Scale</span>
                                </div>
                                <div className="text-[15px] font-medium text-[var(--text-primary)]">
                                    {projectStats.linesOfCode} Lines
                                </div>
                            </div>
                            <div className="p-4 rounded-lg bg-[var(--bg-root)] border border-[var(--border-subtle)]">
                                <div className="flex items-center gap-2 text-[var(--text-tertiary)] mb-1">
                                    <Zap size={14} />
                                    <span className="text-[11px] uppercase tracking-wider">Fixes</span>
                                </div>
                                <div className="text-[15px] font-medium text-[var(--text-primary)]">
                                    {projectStats.importsFixed} Applied
                                </div>
                            </div>
                        </div>

                        {/* GitHub Token Input */}
                        {!repoUrl && (
                            <div className="mb-6">
                                <label className="block text-[13px] font-medium text-[var(--text-secondary)] mb-2">
                                    GitHub Personal Access Token
                                </label>
                                <div className="relative">
                                    <Key size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-tertiary)]" />
                                    <input
                                        type="password"
                                        value={githubToken}
                                        onChange={(e) => setGithubToken(e.target.value)}
                                        placeholder="ghp_..."
                                        className="w-full pl-10 pr-4 py-2.5 rounded-lg border border-[var(--border-default)] bg-[var(--bg-panel)] text-[13px] text-[var(--text-primary)] placeholder-[var(--text-tertiary)] focus:border-[var(--accent-primary)] focus:outline-none focus:ring-1 focus:ring-[var(--accent-primary)] transition-all"
                                    />
                                </div>
                                <p className="text-[11px] text-[var(--text-tertiary)] mt-1">
                                    <a href="https://github.com/settings/tokens/new" target="_blank" rel="noopener noreferrer" className="text-[var(--accent-primary)] hover:underline">
                                        Create token here
                                    </a> (needs 'repo' scope)
                                </p>
                            </div>
                        )}

                        {/* Success Message */}
                        {repoUrl && (
                            <div className="mb-6 p-4 rounded-lg bg-[var(--accent-primary)]/10 border border-[var(--accent-primary)]/20 shadow-[0_0_20px_var(--accent-glow)]/5">
                                <div className="flex items-center gap-2 mb-2">
                                    <CheckCircle2 size={16} className="text-[var(--accent-primary)]" />
                                    <span className="text-[13px] font-bold uppercase tracking-widest text-[var(--accent-primary)]">Repository Created!</span>
                                </div>
                                <a
                                    href={repoUrl}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-[12px] text-[var(--text-primary)] hover:text-[var(--accent-primary)] font-mono break-all underline"
                                >
                                    {repoUrl}
                                </a>
                            </div>
                        )}

                        {/* Actions */}
                        <div className="flex flex-col sm:flex-row gap-3">
                            <button
                                onClick={handleDownload}
                                disabled={isExporting}
                                className="flex items-center justify-center gap-2 px-6 py-2.5 rounded-lg bg-[var(--accent-primary)] text-white font-medium text-[13px] hover:opacity-90 transition-all shadow-lg shadow-[var(--accent-primary)]/20 disabled:opacity-50"
                            >
                                <Download size={16} />
                                {isExporting ? 'Generating...' : 'Download ZIP'}
                            </button>

                            <button
                                onClick={handlePushToGitHub}
                                disabled={isCreatingRepo || !githubToken || !!repoUrl}
                                className="flex items-center justify-center gap-2 px-6 py-2.5 rounded-lg bg-[var(--bg-panel)] border border-[var(--border-default)] text-[var(--text-primary)] font-medium text-[13px] hover:bg-[var(--bg-hover)] transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                <Github size={16} />
                                {isCreatingRepo ? 'Creating...' : repoUrl ? 'Created ✓' : 'Push to GitHub'}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
