import { NextRequest, NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';
import { createClient } from '@supabase/supabase-js';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { projectId, repoName, isPrivate = false, githubToken, accessToken } = body;

        if (!githubToken) {
            return NextResponse.json(
                { error: 'GitHub token is required' },
                { status: 400 }
            );
        }

        // Initialize Octokit with user's token
        const octokit = new Octokit({
            auth: githubToken
        });

        // Create repository
        const { data: repo } = await octokit.repos.createForAuthenticatedUser({
            name: repoName || `loom-project-${Date.now()}`,
            private: isPrivate,
            description: 'Generated by Loom AI',
            auto_init: true
        });

        // Update project in Supabase if projectId is provided
        if (projectId) {
            // Use the access token passed from the client to authorize the request
            // This ensures we respect RLS policies as the authenticated user
            const supabase = createClient(
                process.env.NEXT_PUBLIC_SUPABASE_URL!,
                process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
                accessToken ? {
                    global: {
                        headers: {
                            Authorization: `Bearer ${accessToken}`,
                        },
                    },
                } : undefined
            );

            const { error: updateError } = await supabase
                .from('projects')
                .update({ github_url: repo.html_url })
                .eq('id', projectId);

            if (updateError) {
                console.error('Failed to update project with GitHub URL:', updateError);
                // We don't fail the request since the repo was created, but we log it
            }
        }

        return NextResponse.json({
            repoUrl: repo.html_url,
            cloneUrl: repo.clone_url,
            sshUrl: repo.ssh_url
        });

    } catch (error: any) {
        console.error('GitHub repo creation failed:', error);
        return NextResponse.json(
            { error: error.message || 'Failed to create GitHub repository' },
            { status: 500 }
        );
    }
}
